name: BlockBreak
version: '${project.version}'
main: com.github.constmine.plugin.blockbreak.BlockBreak
api-version: 1.18
authors: [ constmine ]
description: 각별님이 만드신 영상 "순발력"을 참고하여 제 맛대로 만들어 보았습니다.

commands:
  bb:
  t: